### PR TITLE
Ensure that should the previous keyframe not contain any components, the keyframe is not incorrectly invalidated

### PR DESCRIPTION
**Pull request by hedss**
Connects-to: #9

Change-type: patch
---- Autogenerated Waffleboard Connection: Connects to #9

### CODE REVIEW

**Review by brownjohnf — APPROVED** [review]

**Comment by lurch** [comment]
...and presumably this doesn't mean that if a new keyframe removes all the components, that it'll be considered valid? ;)

**Comment by brownjohnf** [comment]
It probably will be.

**Comment by hedss** [comment]
If someone purposefully removes all components, then how do we know it's not valid? It might be?

**Comment by brownjohnf** [comment]
Yeah, I'm not worried. There will be human code review on this as well,
presumably.

**Comment by lurch** [comment]
> If someone purposefully removes all components, then how do we know it's not valid? It might be?

True, I hadn't considered that. Apologies for sticking my nose in ;)

**Pull request merged**
